### PR TITLE
Update the activity with sugarlabs/turtleart-activity and apply mexico patches

### PR DESCRIPTION
**Pull request by kiy4h**
I cloned https://github.com/sugarlabs/turtleart-activity/ to local and cherry-picked those three commits:
```
fbc466be30368b8e2ebd15445a5a5612acfcf231
8fbb3c7b686d607e441fb1084fe96f0a3209168d
acfeb4b519b796f51cb8986ae76bcd92217780b1
```
from the mexico branch (https://github.com/sugarlabs/turtleart-activity/tree/mexico) and resolved a few merge conflicts, then I ran ./pygi-convert.sh in the directory.
And finally, I pushed to the fork of TortugadeMexico.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks, I will review what you did tomorrow, my time.

**Comment by srevinsaju** [comment]
@Kiy4h, you have committed `turtleblocks.py`. turtleblocks.py, turtleblocks and turtleblocks.desktop are currently not working and hadn't been ported to Python3 because of telepathy deprecation. To compat this all references of `telepathy` had to be refactored to `TelepathyGLib` as mentioned in the Python 3 Porting Guide. Some files have not been ported to TelepathyGLib. This includes the files in `TurtleArt/ta*.py`. There are 17 instances of `telepathy` in this port.  But I think `textchannelwrapper` would be enough I suppose to manage collabortation. @quozl ? The other sources can be removed.

Tested logs contain Errors. It might be helpful
```

(sugar-activity3:14622): Gtk-WARNING **: 18:14:17.513: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity3:14622): Gtk-WARNING **: 18:14:17.514: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
1576682058.647784 WARNING root: No icon with the name save-macro was found in the theme.
1576682058.649044 WARNING root: No icon with the name save-macro was found in the theme.
reskin already in palette extras, skipping...
Traceback (most recent call last):
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 547, in do_eraser_cb
    self.restore_challenge()
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 553, in restore_challenge
    self._load_level()
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 1831, in _load_level
    self.tw.canvas.setxy(int(-Gdk.Screen.width() / 2), 0,
AttributeError: 'TurtleGraphics' object has no attribute 'setxy'
Traceback (most recent call last):
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 547, in do_eraser_cb
    self.restore_challenge()
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 553, in restore_challenge
    self._load_level()
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 1831, in _load_level
    self.tw.canvas.setxy(int(-Gdk.Screen.width() / 2), 0,
AttributeError: 'TurtleGraphics' object has no attribute 'setxy'
Traceback (most recent call last):
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 581, in do_stop_cb
    self.stop_turtle_button.set_icon('hideshowoff')
AttributeError: 'ToolButton' object has no attribute 'set_icon'

Traceback (most recent call last):
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 547, in do_eraser_cb
    self.restore_challenge()
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 553, in restore_challenge
    self._load_level()
  File "/home/srevinsaju/Totru/TortugadeMexico/TurtleArtActivity.py", line 1831, in _load_level
    self.tw.canvas.setxy(int(-Gdk.Screen.width() / 2), 0,
AttributeError: 'TurtleGraphics' object has no attribute 'setxy'

```  
The Error is caused by the difference in the TurtleArtActivity.py on the master branch of `turtleart-activity` and `Tortugade-Mexico` which is obvious to be different. 
@quozl , I would be happy to know what makes Tortugade different from TurtleArts.

This might help, I am stuck with fixing collaboration. you can cherry pick TelepathyGLib port commits https://github.com/sugarlabs/turtleart-activity/pull/73

**Comment by quozl** [comment]
I agree with everything up to https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/d4e6b9f68e98a63b1a85a0ad1a9219539c1fc49b and have merged that.  I'm now working on the next few commits.

**Comment by quozl** [comment]
@Kiy4h, https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/5a128895c070ff6b6c91c0eaa01147891f44640a adds conflict markers, which means you hadn't finished it before making the commit, instead you removed the conflict markers in further commits.

Is suboptimal because we can't use `git bisect` in future, and can't easily cherry-pick again next time we have to synchronise the two source repositories.

Better is to get to the same place but by better series of commits.

Please start a new branch as at the new _master_ d4e6b9f68e98a63b1a85a0ad1a9219539c1fc49b and try cherry-pick fbc466be30368b8e2ebd15445a5a5612acfcf231 again, but this time review the conflicts and fix them.  Use an IDE that lets you see the change about to be committed, and lets you select specific lines to be included in a commit.  I use emacs with magit for this, but there's gotta be other tools out there, I just don't know what they are yet.

Also, in comparing `git diff  d4e6b9f..c3de7d5` there are some important changes you've made that should be separated out and applied to both repositories.  Because these aren't really part of the change set from TurtleBlocks to Tortuga de Mexico, and to have them here only makes the latter depart from the former.

@srevinsaju, thanks for testing.  Your work on https://github.com/sugarlabs/turtleart-activity/pull/73 to fix the activity for use in GNOME is yet to be merged, but when it is then I'd expect it to be also added to this activity.

**Comment by quozl** [comment]
Fixes https://github.com/sugarlabs/TortugadeMexico/issues/2

**Comment by kiy4h** [comment]
Sorry, that was due to my habit of autosaving a modified file.
I'm used to using VSCode as my code editor, I'll try to fix this mess by rebasing. Thanks for the detailed instruction!

**Comment by Kiy4h** [comment]
Sorry, that was due to my habit of autosaving a modified file.
I'm used to using VSCode as my code editor, I'll try to fix this mess by creating a new branch and change the PR's base branch. Thanks for the detailed instruction!

**Comment by quozl** [comment]
Thanks.  I've taken your late porting changes that were in c2de7d5 and not in 0d0c724 and added them to the TurtleBlocks _master_ branch as https://github.com/sugarlabs/turtleart-activity/commit/9335bcdc64e379da54d051920aaf5319796be9dd ("Late changes for porting to GTK 3").

Next I'll review and test just the two patches you've added here.

**Comment by kiy4h** [comment]
That was quick! Should I also apply the changes to this repository (in this PR)?

**Comment by quozl** [comment]
@Kiy4h, if you like, doesn't matter, we can do it later.  Now to review your two new patches against the previous patches; I set them side by side and scrolled down each pair;

* https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/0d0c724a206927803d950a23c1b29def1e060f9d as compared with https://github.com/sugarlabs/turtleart-activity/commit/8fbb3c7b686d607e441fb1084fe96f0a3209168d, is fine

* nothing as compared with https://github.com/sugarlabs/turtleart-activity/commit/acfeb4b519b796f51cb8986ae76bcd92217780b1, is fine, as it is included in https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/ccbcfdb87719dc70c3e928df9fa46fce5e45d1b9,

* https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/ccbcfdb87719dc70c3e928df9fa46fce5e45d1b9 as compared with https://github.com/sugarlabs/turtleart-activity/commit/fbc466be30368b8e2ebd15445a5a5612acfcf231
  * [ ] `self._level` and `self._custom_filepath` are not initialised,
  * [ ] `help_animation` is missing,
  * [ ] `_help_next` is missing,

At this point I stopped looking; whatever method you used to cherry-pick and resolve conflicts didn't work, or there has been a huge redesign of the change.

So please check you have properly integrated each change from https://github.com/sugarlabs/turtleart-activity/commit/fbc466be30368b8e2ebd15445a5a5612acfcf231 adjusted as necessary for changes since that patch.

The way I would do this is start a new branch as of 0d0c724, use `git rebase -i` to reverse the order of the last two patches, make changes by hand while reading them from https://github.com/sugarlabs/turtleart-activity/commit/fbc466be30368b8e2ebd15445a5a5612acfcf231, and make commits for each major change.  You would end up with a series of patches to show your work, which could be later collapsed into one.

**Comment by walterbender** [comment]
File "/home/walter/Activities/TortugadeMexico/TurtleArt/talogo.py", line 26, in <module>
    import urllib.request, urllib.error, urllib.parse
ImportError: No module named request

Maybe grab the tautils.py from turtle-activity ???
import urllib2

**Comment by quozl** [comment]
Thanks.  Reviewed https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/ae927f2464363a8b40b608c1a13f77446730fa3d against https://github.com/sugarlabs/turtleart-activity/commit/fbc466be30368b8e2ebd15445a5a5612acfcf231;

* there's at least one call to gobject that hasn't been ported; remember than in applying this old patch, any new lines have to be ported to GTK 3 and ported to Python 3, because those two portings also happened along the mainline of descent since the patch was originally written,
* the code fragment that creates the help button and connects to _do_help_cb is present in the old patch but missing in your patch,
* the next two patch bands are missing, including the only call to _make_confusion_combo.

I stopped at that point.

Please make sure you check your work; set the two patches side by side and work through every change.  Don't rely on automation (e.g. git) to achieve this.  You have to understand the reason for every change, and if you don't yet then work on that until you do.  If you have questions on specific changes in the original patch, point them out and ask.

**Comment by kiy4h** [comment]
@quozl excuse me, why does this error appear when I ran sugar-activity3 and clicked on the snail button in both TortugadeMexico and turtleart-activity?
```
Traceback (most recent call last):
  File "/home/kiyah/Activities/TortugadeMexico/TurtleArt/talogo.py", line 627, in doevalstep
    next(self.step)
  File "/home/kiyah/Activities/TortugadeMexico/TurtleArt/talogo.py", line 596, in _evalsym
    result = self.cfun.fcn(self, *self.arglist)
  File "/home/kiyah/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 327, in __call__
    new_prim.call_afterwards(*new_args, **new_kwargs)
  File "/home/kiyah/Activities/TortugadeMexico/TurtleArt/tabasics.py", line 1312, in after_move
    self.tw.coord_scale)
  File "/home/kiyah/Activities/TortugadeMexico/TurtleArt/talogo.py", line 1090, in update_label_value
    for block in self.value_blocks_to_update[name]:
AttributeError: 'LogoCode' object has no attribute 'value_blocks_to_update'
```
Is this a known issue, or did I miss installing something?

screenshot

**Comment by walterbender** [comment]
can you reproduce the same error on the regular turtle-blocks activity?

**Comment by kiy4h** [comment]
@walterbender Yes, happens on both turtle activities.

**Comment by walterbender** [comment]
I pushed a fix to turtle-activity that can also be applied here.

https://github.com/walterbender/turtle-activity/commit/d6e04f6e90cb954dbb13d987109658d6c6f96b16

There seem to be more problems with turtle-activity that are resolved in my version. Not sure how we got out of sync.

**Comment by kiy4h** [comment]
During testing, I've encountered many errors and exceptions.

~~I'm guessing this one was caused by the ToolButton module itself, not related to the turtle activity~~

EDIT 1: This happens when you were trying to choose a block palette, and this error makes it impossible to show most of the blocks.

EDIT 2: They were already implemented in both turtle activities, https://github.com/sugarlabs/turtleart-activity/blob/9335bcdc64e379da54d051920aaf5319796be9dd/TurtleArt/util/helpbutton.py#L53 is the one from turtle activity.
I found out that the block palette doesn't want to open after I ran my turtle blocks (in my case, I used the 🐌 button), but I haven't found a fix.

EDIT 3: The only way to switch between block palettes is by using the arrow, clicking from the palette choices does nothing.

EDIT 4: After reading https://developer.sugarlabs.org/sugar3/sugar3.graphics.toolbutton.html , I changed `set_current_palette` to `set_palette` (https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/e41c3a5f35ae796625e28beb6c30d91158120794/src/sugar3/graphics/toolbutton.py#L224) and it settled things up a bit. Except now `self._palette` is a string, and it returns a lot of `AttributeError: 'str' object has no attribute 'props', 'popdown', 'is_up',` etc

image
```
Traceback (most recent call last):
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArtActivity.py", line 485, in do_palette_buttons_cb
    self._help_button.set_current_palette(palette_names[i])
AttributeError: 'ToolButton' object has no attribute 'set_current_palette'
```

This one often appears in mexico turtle, but it doesn't happen in turtleart-activity:
```
Traceback (most recent call last):
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArtActivity.py", line 1769, in _levels_cb
    self._load_level()
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArtActivity.py", line 1780, in _load_level
    self.tw.canvas.setxy(int(-Gdk.Screen.width() / 2), 0,
AttributeError: 'TurtleGraphics' object has no attribute 'setxy'
```
Should I grab (necessary changes from) the `tacanvas.py` from turtleart-activity's `mexico` branch to solve this? 
EDIT: found out that setxy is deprecated, but there's setxy2. What are the difference?

And this one, using the "clean" block:
```
Traceback (most recent call last):
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 629, in doevalstep
    next(self.step)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 598, in _evalsym
    result = self.cfun.fcn(self, *self.arglist)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 322, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 709, in group
    return_val = prim()
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 322, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 1054, in clear_value_blocks
    self.update_label_value(name)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 1072, in update_label_value
    for block in self.value_blocks_to_update[name]:
KeyError: 'xcor'
```
I'm still trying to find out what caused this one, since it doesn't happen in turtleart-activity.

EDIT: The "clean" block only works if you clean (Ctrl+E) first.

image

**Comment by Kiy4h** [comment]
During testing, I've encountered many errors and exceptions.

I'm guessing this one was caused by the ToolButton module itself, not related to the turtle activity:
```
Traceback (most recent call last):
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArtActivity.py", line 485, in do_palette_buttons_cb
    self._help_button.set_current_palette(palette_names[i])
AttributeError: 'ToolButton' object has no attribute 'set_current_palette'
```

This one was caused by using the "setxy" block, but it doesn't happen in turtleart-activity:
```
Traceback (most recent call last):
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArtActivity.py", line 1769, in _levels_cb
    self._load_level()
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArtActivity.py", line 1780, in _load_level
    self.tw.canvas.setxy(int(-Gdk.Screen.width() / 2), 0,
AttributeError: 'TurtleGraphics' object has no attribute 'setxy'
```
Should I grab (necessary changes from) the `tacanvas.py` from turtleart-activity's `mexico` branch to solve this? 

And this one, using the "clear" block:
```
Traceback (most recent call last):
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 629, in doevalstep
    next(self.step)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 598, in _evalsym
    result = self.cfun.fcn(self, *self.arglist)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 322, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 709, in group
    return_val = prim()
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/taprimitive.py", line 322, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 1054, in clear_value_blocks
    self.update_label_value(name)
  File "/home/kiy4h/Activities/TortugadeMexico/TurtleArt/talogo.py", line 1072, in update_label_value
    for block in self.value_blocks_to_update[name]:
KeyError: 'xcor'
```
I'm still trying to find out what caused this one, since it doesn't happen in turtleart-activity.

**Comment by quozl** [comment]
Thanks.  Sorry for the delay.  I've reviewed your changes since my last review.  I think you're missing the point; so I'll try to explain again and suggest something new.

_Long reply_.

Back a few years ago, TurtleArt was copied and changed, adding a new feature, which was named TortugadeMexico.  The change was entirely described within the three commits, of which the largest is https://github.com/sugarlabs/turtleart-activity/commit/fbc466be30368b8e2ebd15445a5a5612acfcf231.  This commit is to 36 files, with 6471 deletions and 416 insertions.

Since then, TurtleArt has undergone significant change; especially a Port to GTK 3 and a Port to Python 3.  A series of 880 commits, to 454 files, 174351 insertions, and 117192 deletions.

TortugadeMexico has not undergone this change.

To port the TortugadeMexico activity to GTK 3 and Python 3, it is necessary to bring the two chains of history back together.

This can't be done mechanically using "git merge", because too much has changed.  The Port to GTK 3 means that some of the 416 insertions are now wrong.

There's three different ways this kind of merge can be completed;

1. try a "git merge" and then figure out what needs fixing; a barely possible task, as it requires certainty about what every one of the 883 commits intended to do,
1. apply each of the 880 commits one by one to TortugadeMexico; an insanely long task that none of us would try first, but might eventually be worth trying,
1. rewrite the original change for the latest TurtleArt, (this is what I was guiding you through), which should be working out how those 416 insertions can be rewritten for GTK 3 and Python 3, while only guided by understanding the largest of the other 880 commits.

There's an additional way I hadn't mentioned.  Take the original https://github.com/sugarlabs/turtleart-activity/commit/fbc466be30368b8e2ebd15445a5a5612acfcf231 commit, explain every single change, and then break it into lots of smaller commits.  Firstly, commits that won't have any bugs, like the removal of plugins.  Then, commits that change defaults, like whether blocks are hidden.  Finally, commits that add the new feature, and a separate commit that enables the feature.

Then each commit can be viewed in order to make changes with the same effect to the latest TurtleArt.

Don't be deceived though; there's no short cut.  It is a really hard task, because TurtleArt is really big, and has been changed a lot.

**Comment by kiy4h** [comment]
Thanks, I can understand better now. I'll retake this later after a few tasks or so, I have to get more experiences with porting and GTK3 before getting back to doing this again.

**Comment by Hrishi1999** [comment]
Tested https://github.com/sugarlabs/TortugadeMexico/pull/4/commits/a18881a28ddde231d12616f24b50764dba4457c7. 
Capture
This occurs when pressing the stop button, then hide blocks button.

**Comment by kiy4h** [comment]
@Hrishi1999 Sorry about that, and thanks for finding it out. I have fixed it on 2c43226.

**Comment by kiy4h** [comment]
@quozl @Hrishi1999 I've decided to take the 3rd way. (from https://github.com/sugarlabs/TortugadeMexico/pull/4#issuecomment-569187200)

What I did was:
- cherry-pick the ta/mexico commits (from turtleart-activity) and fix merge conflicts very carefully, (724567d, 7a5f024)
- run pygi-convert.sh, (77d7eb2)
- run 2to3, (8243401)
- debug and fix multiple times (f4b2594,  1faac3b, 9182927, 2c43226)

**Comment by tchx84** [comment]
Hi @Kiy4h, I did a quick QA ran and found a few issues:

== first ==

1. run ./turtleblocks
2. click on "Tools" menu
3. click on "Show palette" item.

The following error shows:

Traceback (most recent call last):
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/turtleblocks.py", line 867, in _do_palette_cb
    if self.current_palette == len(self.tw.palettes):
AttributeError: 'TurtleArtWindow' object has no attribute 'palettes'

Also, noticed that each time I click on "Show palette" the selected blocks type moves to the next one.

== second ==

1. run ./turtleblocks
2. click on "View" menu
3. click on "Cartesian coordinats" item.
4. then repeat, but click on "Polar coordinats" item.

Then, the two coordinates overlaps. I assume it should clear the previous one.

== third ==

1. run ./turtleblocks
2. click on "Edit" menu
3. click on "Copy" item.

The following error shows:

Traceback (most recent call last):
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tawindow.py", line 1234, in _buttonpress_cb
    Gdk.ModifierType.CONTROL_MASK, x, y)
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tawindow.py", line 1299, in button_press
    if self._look_for_a_blk(spr, x, y):
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tawindow.py", line 1369, in _look_for_a_blk
    self._block_pressed(x, y, blk)
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tawindow.py", line 2018, in _block_pressed
    clipboard.set_text(text)
TypeError: Gtk.Clipboard.set_text() takes exactly 3 arguments (2 given)

== fourth ==

1. run ./turtleblocks
2. click on "File" menu
3. click on "Show sample projects" item.
4. clock on the first sample.
5. click on "Turtle" menu.
6. click on "Run" item.

The following error shows:

WARNING: unknown block name showblocks
Traceback (most recent call last):
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tawindow.py", line 3020, in __run_stack
    code = self.lc.generate_code(top, self.just_blocks())
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/talogo.py", line 315, in generate_code
    code = self._blocks_to_code(b)
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/talogo.py", line 379, in _blocks_to_code
    code.extend(self._blocks_to_code(b))
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/talogo.py", line 352, in _blocks_to_code
    dock = blk.docks[0]
IndexError: list index out of range

== fifth ==

1. run ./turtleblocks
2. click on "File" menu
3. click on "Export as" item.
3. click on "Logo" item.

The following error shows:

Traceback (most recent call last):
  File "/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/turtleblocks.py", line 737, in _do_save_logo_cb
    if isinstance(filename, unicode):
NameError: name 'unicode' is not defined

NOTE: some of these could be regressions (or not), but the third and fifth looks like python/gtk ports issues.

**Comment by kiy4h** [comment]
@tchx84 Thanks for reviewing, I've missed those errors when testing. I'll start fixing soon.

**Comment by kiy4h** [comment]
@tchx84 Do I have to run turtle by running `./turtleblocks`?

Running the activity with `sugar-activity3`, I couldn't reproduce first and third, and the fifth *is able to be reproduced,* but with a different form of error.

About the second, it also happens in turtleart-activity, which I think is better to fix them from the main repository.

But I'm able to reproduce the fourth, which shouldn't be too hard to fix.

**Comment by kiy4h** [comment]
@tchx84 I have fixed the first one on a09aa48.

For the second one, I'll create an issue on the turtleart-activity repository soon.

The third, I added the *third* (second) parameter on f714edc.

The fourth was caused by the turtle_block_extras.py which didn't load, my fix on that has been squashed with 77b6758.

The fifth one was fixed on 45d8d92, it was clearly because of not running 2to3 in subfolders.

**Review by tchx84 — CHANGES_REQUESTED** [review]
Great job fixing those. I have a few more comments.

== sixth ==

1. run ./turtleblocks
2. immediately you will see these warnings:

```
/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/turtleblocks.py:36: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tawindow.py:38: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import PangoCairo
/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tagplay.py:28: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
/var/home/tchx84/Devel/TortugadeMexico/TurtleArt/tagplay.py:31: PyGIWarning: GstVideo was imported without specifying a version first. Use gi.require_version('GstVideo', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkX11, GstVideo  # noqa: F401
```
Please add these where needed https://github.com/sugarlabs/activity-abacus/blob/2040feef147fe80e7170cd3140a1bc0c7cdb6f99/AbacusActivity.py#L21

== seventh ==

I see that the clipboard error is gone, but I noticed it's not really copying anything. Please double check with Walter how it is supposed to work. In any case, make sure to use the right clipboard like is done in https://github.com/sugarlabs/activity-abacus/blob/2040feef147fe80e7170cd3140a1bc0c7cdb6f99/AbacusActivity.py#L347

== eight ==

I noticed  the size of the canvas is a bit too big, e.g. I am running in 720p. Not sure if it's a regression though.

**Comment by kiy4h** [comment]
sixth: fixed on 21764b9, those warnings are easy to suppress. 

seventh: fixed on 6ce9155. FYI: the copy-paste feature doesn't work in the main repository either. (https://github.com/sugarlabs/turtleart-activity/)

eight: I don't think that's a regression since I couldn't reproduce the case, but I might want to dig around and see.
It might be due to different OS versions, mine is Sugar Live Build on Debian.

**Comment by kiy4h** [comment]
Collaboration hasn't been fixed yet (or is broken due to the changes I made), but I think that should be another issue.

Some errors were emitted when sharing the activity with another user, and there were many unsynchronized things between the users.

The tacollaboration.py doesn't load on the GNOME app, due to some errors in the script. 

*My assumption: Collaboration is now a mess due to me trying to fix the python3 and gtk3 mess*

But it is possible and is more likely that it was already broken from before I have made any changes, even the collaboration doesn't work properly on the turtleart-activity repository.

**Comment by srevinsaju** [comment]
> _My assumption: Collaboration is now a mess due to me trying to fix the python3 and gtk3 mess_

Yup, fixing Collaboration is one of the reason the port to GTK on turtle-art remained unfinished, :). Collaboration on turtle-art activity was working before it was ported to `TelepathyGLib`

**Comment by quozl** [comment]
Rebased by hand based on your branch and pushed to master.  Thanks!

**Comment by BharathSatheeshKumar** [comment]
I cloned https://github.com/sugarlabs/turtleart-activity/ to local and cherry-picked those three commits:

`fbc466be30368b8e2ebd15445a5a5612acfcf231
8fbb3c7b686d607e441fb1084fe96f0a3209168d
acfeb4b519b796f51cb8986ae76bcd92217780b1`

from the mexico branch (https://github.com/sugarlabs/turtleart-activity/tree/mexico) and resolved a few merge conflicts, then I ran ./pygi-convert.sh in the directory. And finally, I pushed to the fork of TortugadeMexico.

**Pull request closed without merging**
